- name: Delete VM
  community.vmware.vmware_guest:
    hostname: "{{ vsphere_host }}"
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_pass }}"
    validate_certs: false
    name: "{{ vm_name }}"
    state: absent
    force: true
  delegate_to: localhost
